#!/bin/bash
#SBATCH --nodes=2
#SBATCH --time=0:30:00
#SBATCH --constraint=cpu
#SBATCH --qos=debug
#SBATCH --account=m4680 

module load python cray-hdf5/1.14.3.1 cray-netcdf/4.9.0.13
conda activate firm3d
srun -n 240 -c 1 python map_alone.py
