#!/bin/bash
#SBATCH --nodes=1
#SBATCH --time=0:30:00
#SBATCH --constraint=cpu
#SBATCH --qos=debug
#SBATCH --account=m4680 

module load python cray-hdf5/1.14.3.1 cray-netcdf/4.9.0.13
conda activate equilibrium_map_firm3d
srun -n 128 -c 1 python passing_map_perturbed.py