name: NVIDIA GPU workflow
on:
  pull_request:
    types:
      - [labeled, synchronize]

jobs:
  tests:
    if: contains(github.event.pull_request.labels.*.name, 'GPU CI')
    runs-on:
      group: GPU-runner
    steps:
      - name: Check GPU is available
        run: nvidia-smi

