name: NVIDIA GPU workflow
on:
  push:
    branches:
      - gpu
      - master
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  tests:
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'GPU CI')
    runs-on: [GPU-runner]
    steps:
      - uses: actions/checkout@v4

      - name: Check GPU is available
        run: nvidia-smi

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libboost-all-dev libopenmpi-dev libnetcdf-dev libhdf5-dev libnetcdf-c++4-dev libgsl-dev pkg-config nvidia-cuda-toolkit
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install netCDF4 cmake ninja "pybind11<=2.13.6" setuptools wheel pandas
          NVCC_PATH=$(which nvcc)          
          echo "Using NVCC at: $NVCC_PATH"

          export CUDACXX=$NVCC_PATH
          pip install -v --no-build-isolation -e ".[dev]" 2>&1 | tee install.log
          pip install coverage
        env:
          NETCDF_DIR: /usr
          HDF5_DIR: /usr
          GSL_DIR: /usr

      - name: Confirm GPU bindings were compiled
        run: |
          if ! grep -q "CUDA found. GPU bindings will be compiled." install.log; then
            echo "::error::GPU bindings were not compiled!"
            exit 1
          fi
        shell: bash
      - name: Run tests
        run: |
          python -m pip list
          python -m coverage run -m unittest tests.field.test_gpu
          python -m coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

      - name: Run GPU examples
        run: |
          (cd examples/gpu_boozer_tracing && python gpu_boozer_tracing.py)
          (cd examples/gpu_saw_tracing && python gpu_saw_tracing.py)



